sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XdRbO5jjfOc3wReeCcBzsCYNMb/MWnJWHPZmalX5k9zO6LAo07NVycEbWwTjaPCb8RoCJ1eXIOZyI0di0t1n+9Oz81aK92ccAXLKktH24U3k2tEUSwdMGQFXJDDlH8/rV4sRlKx1xaniGDkg8NF0srvatzh6lr/x2DC5R9us6L8tv71zFfbY9dlMiV+py/F8s9aRC0WdEJqcHenqVr9e0ZjJVRfiIG4w+DnYC5FkRUXf0E9OrR+gC4hVyi8U0wYmMWjd2FHWKHNzUTxTrJzUpyWAccfX4KE2OTNNslsQNCT1+DZlKwF8xRheI6INQzUoHlreGIKZdgZWsuwCWpA3q8Tcp59Vckh6fpNDNYJCH3jY5LjWX0USbU0ynoynxenI7b3j48Rjf0VREcI6wxedPe6WoIvKyBJAwwYe7IoUtn3aXgbD+Ik/rG+5EtU7P6YTAdCffHwCoYLZWXEDFNrBAmwT6dkWQ/miSy8uRB9np7g5oDwTADAyC5DbU50yMAxNqStsY0T5wrgfAMPJZ72yKyVlZv/1s41uXUbuWLOwvOITuMGyY/ynQe7zuUIcTDF3tu/MDRYb1HuKx+MzqdoExMVIXvO6lz09YlLSoAwcJ+NWdFWoiDQmQyObBPS5GgL6fzdxsVsBHMoqrKKdDOWL6AYnPUDV6cGGm27DDzaBFMg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Rise-of-the-Dutch-Republic---Complete--1555-66-_4811
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy